### ISSUE TITLE
Item's roll data creates an actor property instead of having it directly

### ISSUE THREAD

**Issue by Cussa** [vonkow/swords-wizardry#1]
Accordingly to the documentation, items should have a roll like `1d20 + @toHit.v` and `1d4 + @damage.v`. However, this code produces a wrong information, as the `@toHit.v` and `@damage.v` are always zero.

The issue is because the item.getRollData() is getting the actor roll data and adding to an `actor` property.

So this means the correct would be `1d20 + @actor.toHit.v` and `1d4 + @actor.damage.v`. But I don't know if this is the best approach, as it goes different from most systems.

**Comment by vonkow** [comment]
👍 and agree with that last part of your assessment, this behavior was already a candidate for being changed to work the way most other systems work.

**Comment by vonkow** [comment]
Version 2.1.0 does away with user-facing formulas for weapons, adding a to hit modifier field and an "is missile" boolean. These values, in conjunction with the actor's attribute modifiers are now used for to-hit rolls.

**Comment by Cussa** [comment]
Hello, can we reopen this? The damage is still not working properly. It now correctly added the bonus to hit, but the damage bonus is not working.
<img width="921" alt="image" src="https://github.com/user-attachments/assets/ac49220f-2acf-4a87-bc99-5597691f5bac">

**Comment by vonkow** [comment]
It’ll be captured when I convert the TODOs to issues later today. Treating it as part of the work to apply weapon damage to targets.

**Comment by vonkow** [comment]
Damage bonus bug now represented here: https://github.com/vonkow/swords-wizardry/issues/2
